events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /game/ {
            proxy_pass http://game-api:8000/game/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /analytics/ {
            proxy_pass http://analytics-api:8001/analytics/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}